# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jakewendt-simply_pages}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George 'Jake' Wendt"]
  s.date = %q{2011-09-30}
  s.description = %q{A really simple CMS}
  s.email = %q{github@jakewendt.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "generators/simply_pages/USAGE",
    "generators/simply_pages/simply_pages_generator.rb",
    "generators/simply_pages/templates/autotest_simply_pages.rb",
    "generators/simply_pages/templates/controllers/locales_controller.rb",
    "generators/simply_pages/templates/controllers/pages_controller.rb",
    "generators/simply_pages/templates/functional/locales_controller_test.rb",
    "generators/simply_pages/templates/functional/pages_controller_test.rb",
    "generators/simply_pages/templates/images/drag.gif",
    "generators/simply_pages/templates/javascripts/pages.js",
    "generators/simply_pages/templates/migrations/create_pages.rb",
    "generators/simply_pages/templates/models/page.rb",
    "generators/simply_pages/templates/models/page_sweeper.rb",
    "generators/simply_pages/templates/simply_pages.rake",
    "generators/simply_pages/templates/stylesheets/page.css",
    "generators/simply_pages/templates/stylesheets/pages.css",
    "generators/simply_pages/templates/unit/page_test.rb",
    "generators/simply_pages/templates/unit/redcloth_extension_test.rb",
    "generators/simply_pages/templates/views/pages/_child.html.erb",
    "generators/simply_pages/templates/views/pages/_form.html.erb",
    "generators/simply_pages/templates/views/pages/_page.html.erb",
    "generators/simply_pages/templates/views/pages/all.html.erb",
    "generators/simply_pages/templates/views/pages/edit.html.erb",
    "generators/simply_pages/templates/views/pages/index.html.erb",
    "generators/simply_pages/templates/views/pages/new.html.erb",
    "generators/simply_pages/templates/views/pages/show.html.erb",
    "generators/simply_pages/templates/views/pages/translate.js.erb"
  ]
  s.homepage = %q{http://github.com/jakewendt/simply_pages}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A simple CMS}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

